create table if not exists public.tn_discord_members (
  id bigint generated by default as identity primary key,
  channel_id text not null,
  message_id text,
  discord_user_id text,
  username text,
  name text not null,
  uid text,
  role text not null default 'Flex',
  times text[] not null default '{}',
  raw_content text,
  message_created_at timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint tn_discord_members_channel_discord_user_unique unique (channel_id, discord_user_id)
);

create index if not exists idx_tn_discord_members_channel on public.tn_discord_members(channel_id);
create index if not exists idx_tn_discord_members_uid on public.tn_discord_members(uid);

alter table public.tn_discord_members enable row level security;

-- Không cấp SELECT/INSERT/UPDATE/DELETE cho anon/authenticated.
-- Edge Function dùng supabaseAdmin để ghi dữ liệu, còn website nhận dữ liệu qua function.
